牛大爷养殖数据管理系统/app/home/__init__.py
#导入蓝图框架
from flask import Blueprint

#定义蓝图 home时调用app下的home的views视图 访问home就指向home的views
home = Blueprint("home",__name__)
import app.home.views

牛大爷养殖数据管理系统/app/home/views.py
#把home里的额初始化导进来
from . import home
"""
render_template：用于HTML模板，
redirect：跳转至模板，与前面的不同，
flash：闪现提示,
session:就是session啊
"""
from flask import render_template, redirect, url_for, flash, session,request
#从表单脚本中导入 LoginForm 用于表单数据的验证
from app.home.forme import LoginForm,RegistFrom,BuycattleFrom,SellcattleFrom,PwdFrom,UserupFrom,CattleupFrom
#导入数据库模型 导入user 用于读写user表数据
from app.models import Users,Userlog,Sales,Oplog,Notice
from werkzeug.security import generate_password_hash
import uuid
from app import db
import  datetime
import random
from functools import wraps
import os
#用户头像上传的保存地址
#UPLOAD_PATH = os.path.join(os.path.dirname(os.path.dirname(__file__)),r'static\limg\faceimg')
#生产liunx
UPLOAD_PATH = os.path.join(os.path.dirname(os.path.dirname(__file__)),r'static/limg/faceimg')
#买卖记录肉牛保存的地址
#SALES_PATH = os.path.join(os.path.dirname(os.path.dirname(__file__)),r'static\limg\cattleimg')
#生产地址
SALES_PATH = os.path.join(os.path.dirname(os.path.dirname(__file__)),r'static/limg/cattleimg')
'''=====公共部分 登录注册退出 ====='''
#上下文应用处理器 封装全局变量
@home.context_processor
def tpl_extra():
    #定义一个当前时间的类返回时间
    data = dict(
        online_time = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    )
    return data

#定义一个装饰器 访问路由时先验证这个装饰器内的逻辑
def home_login_req(f):
    @wraps(f)
    #自定义函数
    def decorated_function(*args,**kwargs):
        #判断 sessi中是否存在lcs令牌
        if "lcshome" not in session:
            #如果不存在则返回登录界面
            print("不在seesion中")
            return redirect(url_for("home.login",next=request.url))
        #如果存在 返回继续执行访问
        print("在seesion中 开始返回执行函数")
        return f(*args,**kwargs)
    return decorated_function
#进入登录界面
@home.route("/",methods=["GET","POST"])
def login():
    form = LoginForm()
    print("进入登陆函数")
    if form.validate_on_submit(): #提交表单 要验证 前端在提交按钮下添加代码{{form.csrf_token}} app.config设置令牌
        print("进入form.validate_on_submit()")
        data = form.data  #获取表单提交的信息
        print("提交的数据是：",data)
        user = Users.query.filter_by(account=data["account"]).first()
        print('数据库中的姓名1',user.name)
        #调用user中的函数chek_pwd 判断输入的密码和数据库加密后的是否一致 不一致就进入if
        if not user.chek_pwd(data["mima"]):
            flash("密码错误,请重新输入！","err")
            '''
            flash前端闪现通知密码错误 前段增加语句块来显示
            <div>
            {% for msg in get_flashed_messages() %}
                <p style="color: red;">{{msg}}</p>
            {% endfor %}
             </div>
            '''
            return redirect(url_for("home.login"))
        #如果密码一致 存入session把用户名存到session中 并返回主页模板
        session["userface"] = user.face  #前端获取头像名称
        session["account"] = user.account
        session["username"] = user.name
        session["lcshome"] = "q1993"  #此项防止存在管理员的缓存导致可以访问其他页面
        #写入会员登录日志
        userlog =Userlog(
            account=user.account,
            ip = request.remote_addr,
            op='用户 %s 登录' % (session['account'])
        )
        db.session.add(userlog)
        db.session.commit()

        return redirect(url_for("home.index",page=1))
    print("返回登录login界面")
    return render_template('home/login.html',form=form)
#注册
@home.route("/register",methods=["GET","POST"])
def register():
    #from werkzeug.datastructures import CombinedMultiDict
    #form = RegistFrom(CombinedMultiDict([request.form, request.files]))
    form = RegistFrom()
    if form.validate_on_submit():
        print('进入注册提交的数据')
        data = form.data
        if data['face'] != None:
            # 获取上传文件的文件名;
            filena = form.face.data.filename
            # print(str(filename))
            filename = uuid.uuid4().hex + filena
            # 将上传的文件保存到服务器;
            form.face.data.save(os.path.join( UPLOAD_PATH, filename))
            print("touxiang 上传成功")
            user =Users(
                account = data['userId'],
                name = data['userName'],
                pwd = generate_password_hash(data['userpassword']),
                sex = data['sex'],
                weixin= data['weixin'],
                birthday = data['birthday'],
                phone = data['userphone'],
                address = data['userAddress'],
                face = filename,
                info = data['info'],
                uuid = uuid.uuid4().hex
            )
            db.session.add(user)
            print("保存数据")
            db.session.commit()
            flash("注册成功,请点登录","ok")
        else:
            filename = str(random.randint(0,5)) + '.png'
            user = Users(
                account=data['userId'],
                name=data['userName'],
                pwd=generate_password_hash(data['userpassword']),
                sex=data['sex'],
                weixin=data['weixin'],
                birthday=data['birthday'],
                phone=data['userphone'],
                address=data['userAddress'],
                face=filename,
                info=data['info'],
                uuid=uuid.uuid4().hex
            )
            db.session.add(user)
            print("保存数据")
            db.session.commit()
            flash("注册成功,请登录", "ok")
        return redirect(url_for('home.login'))
    return render_template('home/register.html',form=form)
@home.route("/pwd_up",methods=["GET","POST"])
@home_login_req
#修改密码
def pwd_up():
    form = PwdFrom()
    if form.validate_on_submit():
        data = form.data
        user = Users.query.filter_by(name = session["username"]).first()
        user.pwd = generate_password_hash(data["new_pwd"])
        print("修改的新密码为",data["new_pwd"])
        db.session.add(user)
        db.session.commit()
        flash("密码修改成功,请重新登陆！","ok")
        print("密码修改成功")
        return redirect(url_for("home.logout"))
    return render_template("home/pwd_up.html",form=form)

# 退出
@home.route("/logout",methods=["GET","POST"])
@home_login_req
def logout():
    print("进入退出函数")
    userlog = Userlog(
        account=session['account'],
        ip=request.remote_addr,
        op = '用户 %s 退出' % (session['account'])
    )
    db.session.add(userlog)
    db.session.commit()
    # 退出时 把本地缓存的seesion密码去掉
    session.pop("username", None)
    session.pop("userface", None)
    session.pop("account", None)
    session.pop("lcshome", None)
    return redirect(url_for("home.login"))

'''=====首页====='''
#首页
@home.route("/index/<int:page>/",methods=["GET","POST"])
@home_login_req
def index(page=None ):
    if page is None:
        page = 1
    #获取公告 状态为1启用状态的公告数据
    notice = Notice.query.filter_by(state = 1 ).order_by(Notice.priority).paginate(page=page,per_page=10)

    return render_template("home/index.html",notice=notice)

'''=====买卖管理====='''
#买卖记录列表
@home.route("/cattle_list/<int:page>/",methods=["GET"])
@home_login_req
def cattle_list(page=None ):
    if page is None:
        page=1

    #按时间倒序查询 使用自带分页助手paginate返回页码和按多少页分页
    page_data = Sales.query.filter_by(account = session["account"] ).order_by(Sales.addriqi.desc()).paginate(page=page,per_page=10)

    return render_template("home/cattle_list.html",page_data=page_data)
#修改买卖记录
@home.route("/cattle_up/<int:id>/",methods=["GET","POST"])
@home_login_req
def cattle_up(id = None):
    sales = Sales.query.get_or_404(int(id))
    form = CattleupFrom(
        cattlename=sales.cattlename,
        buyprice = sales.buyprice,
        sellprice=sales.sellprice,
        buyweight=sales.buyweight,
        sellweight=sales.sellweight,
        buyunitprice=sales.buyunitprice,
        sellunitprice=sales.sellunitprice,
        buyday = sales.buyday,
        sellday=sales.sellday,
        buynum=sales.buynum,
        sellnum=sales.sellnum,
        buycity=sales.buycity,
        sellcity=sales.sellcity,
        buycontatcs=sales.buycontatcs,
        sellcontatcs=sales.sellcontatcs,
        buyphone=sales.buyphone,
        sellphone=sales.sellphone
    )
    if form.validate_on_submit():
        print("进入修改买卖记录")
        data = form.data
        print("buyprice ", data['buyprice'])
        result = Sales.query.filter_by(id=id).first()
        if data['buyprice'] != "":
            result.buyprice = data['buyprice']
        else:
            result.buyprice = 0
        if data['sellprice'] != "":
            result.sellprice = data['sellprice']
        else:
            result.sellprice = 0
        if data['cattlename'] != "":
            result.cattlename = data['cattlename']
        if data['buyweight'] != "":
            result.buyweight = data['buyweight']
        else:
            result.buyweight = 0
        if data['sellweight'] != "":
            result.sellweight = data['sellweight']
        else:
            result.sellweight = 0
        if data['buyunitprice'] != "":
            result.buyunitprice = data['buyunitprice']
        else:
            result.buyunitprice = 0
        if data['sellunitprice'] != "":
            result.sellunitprice = data['sellunitprice']
        else:
            result.sellunitprice = 0
        if data['buyday'] != "":
            result.buyday = data['buyday']
        else:
            result.buyday = ''
        if data['sellday'] != "":
            result.sellday = data['sellday']
        else:
            result.sellday = ''
        if data['buynum'] != "":
            result.buynum = data['buynum']
        else:
            result.buynum = ''
        if data['sellnum'] != "":
            result.sellnum = data['sellnum']
        else:
            result.sellnum = ''
        if data['buycity'] != "":
            result.buycity = data['buycity']
        else:
            result.buycity = ''
        if data['sellcity'] != "":
            result.sellcity = data['sellcity']
        else:
            result.sellcity = ''
        if data['buycontatcs'] != "":
            result.buycontatcs = data['buycontatcs']
        else:
            result.buycontatcs = ''
        if data['sellcontatcs'] != "":
            result.sellcontatcs = data['sellcontatcs']
        else:
            result.sellcontatcs = ''
        if data['buyphone'] != "":
            result.buyphone = data['buyphone']
        else:

牛大爷养殖数据管理系统/app/templates/home/adminloginlog_list.html
{% extends "home/home.html" %}
{% block content %}
<div class="content-wrapper">
        <!--内容-->
        <section class="content-header">
            <h1>牛大爷养殖管理系统</h1>
            <ol class="breadcrumb">
                <li><a href="#"><i class="fa fa-dashboard"></i> 日志管理</a></li>
                <li class="active">管理员登录日志列表</li>
            </ol>
        </section>
        <section class="content" id="showcontent">
            <div class="row">
                <div class="col-md-12">
                    <div class="box box-primary">
                        <div class="box-header">
                            <h3 class="box-title">管理员登录日志列表</h3>
                            <div class="box-tools">
                                <div class="input-group input-group-sm" style="width: 150px;">
                                    <input type="text" name="table_search" class="form-control pull-right"
                                           placeholder="请输入关键字...">

                                    <div class="input-group-btn">
                                        <button type="submit" class="btn btn-default"><i class="fa fa-search"></i>
                                        </button>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="box-body table-responsive no-padding">
                            <table class="table table-hover">
                                <tbody>
                                <tr>
                                    <th>编号</th>
                                    <th>管理员</th>
                                    <th>登录时间</th>
                                    <th>登录IP</th>
                                </tr>
                                <tr>
                                    <td>1</td>
                                    <td>admin</td>
                                    <td>2017-06-01</td>
                                    <td>192.168.4.1</td>
                                </tr>
                                </tbody>
                            </table>
                        </div>
                        <div class="box-footer clearfix">
                            <ul class="pagination pagination-sm no-margin pull-right">
                                <li><a href="#">首页</a></li>
                                <li><a href="#">上一页</a></li>
                                <li><a href="#">1</a></li>
                                <li><a href="#">2</a></li>
                                <li><a href="#">3</a></li>
                                <li><a href="#">下一页</a></li>
                                <li><a href="#">尾页</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!--内容-->
    </div>
{% endblock %}

牛大爷养殖数据管理系统/app/templates/home/cattle_up.html
{% extends "home/home.html" %}
{% import "ui/home_page.html" as pg %}
{% block content %}
 <div class="content-wrapper">
        <!--内容-->
        <section class="content-header">
            <h1>牛大爷养殖管理系统</h1>
            <ol class="breadcrumb">
                <li><a href="#"><i class="fa fa-dashboard"></i> 买卖管理</a></li>
                <li class="active">买卖记录列表</li>
            </ol>
        </section>
        <section class="content" id="showcontent">
            <div class="row">
                <div class="col-md-12">
                    <div class="box box-primary">
                        <div class="box-header with-border">
                            <h3 class="box-title">买卖记录列表</h3>
                            <div class="box-tools">
                                <div class="input-group input-group-sm" style="width: 150px;">
                                    <input type="text" name="table_search" class="form-control pull-right"
                                           placeholder="请输入关键字...">

                                    <div class="input-group-btn">
                                        <button type="submit" class="btn btn-default"><i class="fa fa-search"></i>
                                        </button>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="box-body table-responsive no-padding">
                            <form method="post">
                            {% for msg in get_flashed_messages(category_filter=["ok"]) %}
                                <div class="alert alert-success alert-dismissable">
                                    <button type="reset" class="close" data-dismiss="alert"></button>
                                    <h4><i class="icon fa fa-check"></i> 操作成功</h4>
                                    {{ msg }}
                                </div>
                            {% endfor %}
                            <table class="table table-hover">
                                <tbody>
                                <tr>
                                    <th>昵称</th>
                                    <th>买/卖总价<a style="font-size:12px"  >（元）</a></th>
                                    <th>买/卖体重<a style="font-size:12px"  >（Kg）</a></th>
                                    <th>买/卖单价<a style="font-size:12px"  >（Kg/元）</a></th>
                                    <th>买/卖日期</th>
                                    <th>买/卖批次</th>
                                    <th>买/卖人</th>
                                    <th>买/卖地点</th>
                                    <th>联系方式</th>
                                    <th>操作事项</th>
                                </tr>
                                <tr>
                                    <td style="width: 5%">{{ form.cattlename }}</td>
                                    <td style="width: 10%">{{form.buyprice}} / {{form.sellprice}}</td>
                                    <td style="width: 8%">{{form.buyweight}} / {{form.sellweight}}</td>
                                    <td style="width: 9%">{{form.buyunitprice}} / {{form.sellunitprice}}</td>
                                    <td style="width: 13%">{{form.buyday}}/ {{form.sellday}}</td>
                                    <td style="width: 13%">{{form.buynum}}/ {{form.sellnum}}</td>
                                    <td style="width: 8%">{{form.buycontatcs}}/{{form.sellcontatcs}}</td>
                                    <td style="width: 10%">{{form.buycity}} / {{form.sellcity}}</td>
                                    <td style="width: 15%">{{form.buyphone}} / {{form.sellphone}}</td>
                                    <td style="width: 5%">
                                        {{form.csrf_token}}
                                        {{form.submit}}
                                    </td>
                                    <td style="width: 5%">
                                        <a class="btn btn-primary" href="{{url_for('home.cattle_list',page=1)  }}" type="submit">返回</a>
                                    </td>
                                </tr>
                                </tbody>
                            </table>
                            </form>
                        </div>
                        <div class="box-footer clearfix">
                            <ul class="pagination pagination-sm no-margin pull-right">
                                {{ pg.page(page_data,'home.cattle_list') }}
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!--内容-->
    </div>
{% endblock %}
{% block js %}
<!--日期选择框-->
<script>
    $(document).ready(function(){
        $('#input_release_time').datepicker({
            autoclose: true,
            format: 'yyyy-mm-dd',
            language: 'zh-CN',
        });
    });
</script>
<script>
    $(document).ready(function(){
        $('#input_release_time1').datepicker({
            autoclose: true,
            format: 'yyyy-mm-dd',
            language: 'zh-CN',
        });
    });
</script>
{% endblock %}

牛大爷养殖数据管理系统/app/templates/home/cattle_view.html
{% extends "home/home.html" %}
{% block content %}

<div class="content-wrapper">
        <!--内容-->
        <section class="content-header">
            <h1>牛大爷养殖管理系统</h1>
            <ol class="breadcrumb">
                <li><a href="#"><i class="fa fa-dashboard"></i> 买卖记录</a></li>
                <li class="active">查看记录</li>
            </ol>
        </section>
        <section class="content" id="showcontent">
            <div class="row">
                <div class="col-md-12">
                    <div class="box box-primary">
                        <div class="box-header">
                            <h3 class="box-title">肉牛详情</h3>
                        </div>
                        <div class="box-body table-responsive no-padding">
                            <table class="table table-hover">
                                <tbody>
                                <tr>
                                    <td class="td_bd">肉牛ID：</td>
                                    <td>{{sales.cattleid}}</td>
                                </tr>
                                <tr>
                                    <td class="td_bd">肉牛昵称：</td>
                                    <td>{{sales.cattlename}}</td>
                                </tr>
                                <tr>
                                    <td class="td_bd">购买时图片：</td>
                                    <td>
                                        <img style="width: 100px" src="{{ url_for('static',filename='limg/cattleimg/' + sales.buycattlefild )}}">
                                    </td>
                                </tr>
                                <tr>
                                    <td class="td_bd">出栏时图片：</td>
                                    <td>
                                        <img style="width: 100px" src="{{ url_for('static',filename='limg/cattleimg/' + sales.sellcattlefild )}}">
                                    </td>
                                </tr>
                                <tr>
                                    <td class="td_bd">肉牛简介：</td>
                                    <td><ul>{{beefinfo.buy}}</ul>
                                        <ul>{{beefinfo.sell}}</ul>
                                    </td>


                                </tr>
                                   <tr>
                                       <td >
                                           <a class="btn btn-primary" href="{{url_for('home.cattle_list',page=1)  }}" type="submit">返回</a>
                                       </td>
                                  </tr>

                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!--内容-->
    </div>
{% endblock %}

牛大爷养殖数据管理系统/app/templates/home/login.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title>牛大爷养殖数据管理系统</title>
    <link rel="stylesheet" href="{{url_for('static',filename='login/css/style.css')}}"/>
</head>
<body class="login_bg">
    <section class="loginBox">
        <header class="loginHeader">
            <h1>牛大爷养殖数据管理系统</h1>
        </header>
        <section class="loginCont">


            <form class="loginForm" method="post">
                 <div>
                {% for msg in get_flashed_messages(category_filter=["ok"]) %}
                <p class="login-box-body" style="color: #00e765">{{ msg }}</p>
                {% endfor %}

                {% for msg in get_flashed_messages(category_filter=["err"]) %}
                 <p class="login-box-body" style="color: #ff0a2a">{{ msg }}</p>
                {% endfor %}

                </div>

                <div class="inputbox">
                    <label >用户名：</label>
                    {{form.account}}
                    {% for err in form.account.errors %}
                    <div>
                        <font style="color:red ">{{err}}</font>
                    </div>
                    {% endfor %}
                </div>
                <div class="inputbox">
                    <label for="mima">密码：</label>
                    {{form.mima}}
                    {% for err in form.mima.errors %}
                         <div>
                             <font style="color:red ">{{err}}</font>
                        </div>
                    {% endfor %}
                </div>
                <div class="subBtn">
                    {{form.submit}}
                    <input type="reset" value="重置"/>
                    {{form.csrf_token}}
                </div>

                <div  float="right" right="85">
                    <a style="color:#22a6d2;font-size:14px; float:right " href="{{url_for('home.register')}}">没有账号</a>
                </div>


            </form>
        </section>
    </section>

</body>
</html>

牛大爷养殖数据管理系统/app/templates/home/sellcattle_add.html
{% extends "home/home.html" %}
{% block content %}

<div class="content-wrapper">
        <!--内容-->
        <section class="content-header">
            <h1>牛大爷养殖管理系统</h1>
            <ol class="breadcrumb">
                <li><a href="#"><i class="fa fa-dashboard"></i> 买卖管理</a></li>
                <li class="active">添加出栏记录</li>
            </ol>
        </section>
        <section class="content" id="showcontent">
            <div class="row">
                <div class="col-md-12">
                    <div class="box box-primary">
                        <div class="box-header with-border">
                            <h3 class="box-title">添加出栏记录</h3>
                        </div>
                        <form method="post" enctype="multipart/form-data">

                            <!-- 闪现消息提醒-->
                                <div >
                                    {% for msg in get_flashed_messages() %}
                                        <p style="color:red;font-size:14px; text-align:center ">{{msg}}</p>
                                    {% endfor %}
                                </div>
                            <div class="box-body">
                            <!--购买记录-->
                            <div>
                                <label class= "form-group" style="width: 8%">肉牛ID：</label>
                                {{ beef.cattleid}}
                            </div>
                            <div>
                                <label class= "form-group" style="width: 8%">肉牛昵称：</label>
                                {{ beef.cattlename}}
                            </div>
                            <div>
                                <label style="width: 8%">出栏时间：</label>
                                {{ form.sellday}} <a style="color: red"> *(必填) </a>
                                    {% for err in form.sellday.errors %}
                                             <span>
                                                 <font style="color:red ">{{err}}</font>
                                            </span>
                                    {% endfor %}
                            </div>
                            <div>
                                <label style="width: 8%" >卖出总价：</label>
                                {{ form.sellprice}}
                                    {% for err in form.sellprice.errors %}
                                             <span>
                                                 <font style="color:red ">{{err}}</font>
                                            </span>
                                    {% endfor %}
                                <span style="color: black"> 元 <a style="color: red"> *(必填) </a></span>
                            </div>
                            <div>
                                <label style="width: 8%">出栏体重：</label>
                                {{ form.sellweight}}
                                    {% for err in form.sellweight.errors %}
                                             <span>
                                                 <font style="color:red ">{{err}}</font>
                                            </span>
                                    {% endfor %}
                                <span style="color: black"> Kg</span>
                            </div>
                             <div>
                                <label style="width: 8%">出栏运费：</label>
                                {{ form.sellfreight}}
                                    {% for err in form.sellfreight.errors %}
                                             <span>
                                                 <font style="color:red ">{{err}}</font>
                                            </span>
                                    {% endfor %}
                                 <span style="color: black"> 元</span>
                            </div>
                             <div>
                                <label style="width: 8%">卖出地点：</label>
                                {{ form.sellcity}}
                                    {% for err in form.sellcity.errors %}
                                             <span>
                                                 <font style="color:red ">{{err}}</font>
                                            </span>
                                    {% endfor %}
                            </div>
                            <div class="">
                                <label style="width: 8%">出栏批次号：</label>
                                {{ form.sellnum}}
                                    {% for err in form.sellnum.errors %}
                                             <span>
                                                 <font style="color:red ">{{err}}</font>
                                            </span>
                                    {% endfor %}
                            </div>
                             <div>
                                <label style="width: 8%">卖出联系人：</label>
                               {{ form.sellcontatcs}}
                                    {% for err in form.sellcontatcs.errors %}
                                             <span>
                                                 <font style="color:red ">{{err}}</font>
                                            </span>
                                    {% endfor %}
                            </div>
                                <div class = "form-group">
                                <label style="width: 8%">联系手机号：</label>
                               {{ form.sellphone}}
                                    {% for err in form.sellphone.errors %}
                                             <span>
                                                 <font style="color:red ">{{err}}</font>
                                            </span>
                                    {% endfor %}
                            </div>

                                <div >
                                <label  style="width: 8%">肉牛图片：</label>
                                    <label class = "form-group" >{{ form.sellcattlefild}}</label>
                                    {% for err in form.sellcattlefild.errors %}
                                             <span>
                                                 <font style="color:red ">{{err}}</font>
                                            </span>
                                    {% endfor %}
                            </div>

                                <div><label></label></div>
                            <div>
                                {{form.csrf_token}}
                                {{ form.submit }}
                                 <tr>
                                       <td >
                                           <a class="btn btn-primary" href="{{url_for('home.cattle_list',page=1)  }}" type="submit">返回</a>
                                       </td>
                                  </tr>
                            </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </section>
    </div>
{% endblock  %}
{% block js %}
<!--日期选择框-->
<script>
    $(document).ready(function(){
        $('#input_release_time').datepicker({
            autoclose: true,
            format: 'yyyy-mm-dd',
            language: 'zh-CN',
        });
    });
</script>
{% endblock %}